name: crawl
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  crawltel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: crawling-for-new-configs
        run: |
          pip install -r Files/requirements.txt
          python3 Files/main.py --save --country --self-check --check
      - name: commit-changes
        run: |
          git config --global user.name "shabane"
          git config --global user.email "m.mohamadshabane@gmail.com"
          git add hub
          git commit -m "[chore](update links)"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
